### ISSUE TITLE
[Feature Request]: new Javascript release

### ISSUE THREAD

**Issue by doug-wade** [American-Soccer-Analysis/itscalledsoccer-js#1]
### What feature would you like to see?

I would like to release a new version of the js client to get https://github.com/American-Soccer-Analysis/itscalledsoccer/pull/34 out in the wild. I _can_ just cut a new release, but I wanted to check in first and see if we want to do anything more rigorous than me running `npm publish` periodically.

**Comment by bgrnwd** [comment]
@doug-wade Now that each library is in a separate repository, it should be much easier to cut new releases for the JS client. 

Not sure if you saw, but I sent a couple of emails asking what you'd like to do with the JS client. We're happy to host it here and give you control of the repo or you're more than welcome to host it under your own GitHub profile, whichever you'd prefer.

**Comment by doug-wade** [comment]
@bgrnwd I sent you a quick email. I am definitely still interested!

**Comment by doug-wade** [comment]
closed as we released a new version today
